### ISSUE TITLE
How about adding SSN?

### ISSUE THREAD

**Issue by qwerty1917** [mingrammer/commonregex#2]
:sparkles::sparkles: Social Security Number :sparkles::sparkles:

**Comment by mingrammer** [comment]
Sounds good. I'll add it soon :D

**Comment by qwerty1917** [comment]
U Korean I Korean & Conversation on english. what a fun

**Comment by mingrammer** [comment]
I've added it on https://github.com/mingrammer/commonregex/commit/457f293efbab60507fe32e55787260350c7a6adb

But, it supports weak SSN now. (not strictly)
