### ISSUE TITLE
In correct Mac regex

### ISSUE THREAD

**Issue by Umarhayat3** [mingrammer/commonregex#23]
I was look at the mac regex and found that the regex in your code does not take care of this case: 
`a4:5e:60:d4:03-fb`. Where there is mixture of : and - . thanks

**Comment by mingrammer** [comment]
I'll check it!

**Comment by mingrammer** [comment]
It works with `a4:5e:60:d4:03-fb`. How did you test it?

**Comment by mingrammer** [comment]
I close this issue :). Please re-open if this issue occurs again.
