### ISSUE TITLE
Precompiled version

### ISSUE THREAD

**Issue by bep** [mingrammer/commonregex#8]
It would be nice if the funcs could use a precompiled regexp. For speed.

**Comment by mingrammer** [comment]
Do you know a way for using the precompiled regexp as `Constant`?

**Comment by bep** [comment]
No, they're not constants, but I'm not sure why that is important. I would:

* Keep the string constants as is today.
* Create vars for the compiled regexps (just keep them unexported, I guess), create them in `func init()`
* Use the vars from all the funcs.

**Comment by mingrammer** [comment]
Sounds good. Using the `init()` is a great idea.
So, I'll work for that soon. Thank you for giving a tip.

**Comment by bep** [comment]
Thinking about it, you could just create them directly with the `MustCompile` func and drop the init.

**Comment by mingrammer** [comment]
@bep It is using the precompiled regexps now. : 8ba7634c336cdb5a9a6358683689eb05cd1c5a03
